/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v0alpha0

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	apiv0alpha0 "sigs.k8s.io/wg-ai-gateway/prototypes/internal/backend/api/v0alpha0"
)

// XBackendDestinationLister helps list XBackendDestinations.
// All objects returned here must be treated as read-only.
type XBackendDestinationLister interface {
	// List lists all XBackendDestinations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv0alpha0.XBackendDestination, err error)
	// XBackendDestinations returns an object that can list and get XBackendDestinations.
	XBackendDestinations(namespace string) XBackendDestinationNamespaceLister
	XBackendDestinationListerExpansion
}

// xBackendDestinationLister implements the XBackendDestinationLister interface.
type xBackendDestinationLister struct {
	listers.ResourceIndexer[*apiv0alpha0.XBackendDestination]
}

// NewXBackendDestinationLister returns a new XBackendDestinationLister.
func NewXBackendDestinationLister(indexer cache.Indexer) XBackendDestinationLister {
	return &xBackendDestinationLister{listers.New[*apiv0alpha0.XBackendDestination](indexer, apiv0alpha0.Resource("xbackenddestination"))}
}

// XBackendDestinations returns an object that can list and get XBackendDestinations.
func (s *xBackendDestinationLister) XBackendDestinations(namespace string) XBackendDestinationNamespaceLister {
	return xBackendDestinationNamespaceLister{listers.NewNamespaced[*apiv0alpha0.XBackendDestination](s.ResourceIndexer, namespace)}
}

// XBackendDestinationNamespaceLister helps list and get XBackendDestinations.
// All objects returned here must be treated as read-only.
type XBackendDestinationNamespaceLister interface {
	// List lists all XBackendDestinations in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv0alpha0.XBackendDestination, err error)
	// Get retrieves the XBackendDestination from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv0alpha0.XBackendDestination, error)
	XBackendDestinationNamespaceListerExpansion
}

// xBackendDestinationNamespaceLister implements the XBackendDestinationNamespaceLister
// interface.
type xBackendDestinationNamespaceLister struct {
	listers.ResourceIndexer[*apiv0alpha0.XBackendDestination]
}
