/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v0alpha0

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	wgaigatewayapiv0alpha0 "sigs.k8s.io/wg-ai-gateway/api/v0alpha0"
	versioned "sigs.k8s.io/wg-ai-gateway/k8s/client/clientset/versioned"
	internalinterfaces "sigs.k8s.io/wg-ai-gateway/k8s/client/informers/externalversions/internalinterfaces"
	apiv0alpha0 "sigs.k8s.io/wg-ai-gateway/k8s/client/listers/api/v0alpha0"
)

// BackendInformer provides access to a shared informer and lister for
// Backends.
type BackendInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv0alpha0.BackendLister
}

type backendInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBackendInformer constructs a new informer for Backend type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBackendInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBackendInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBackendInformer constructs a new informer for Backend type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBackendInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AinetworkingV0alpha0().Backends(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AinetworkingV0alpha0().Backends(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AinetworkingV0alpha0().Backends(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AinetworkingV0alpha0().Backends(namespace).Watch(ctx, options)
			},
		},
		&wgaigatewayapiv0alpha0.Backend{},
		resyncPeriod,
		indexers,
	)
}

func (f *backendInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBackendInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *backendInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&wgaigatewayapiv0alpha0.Backend{}, f.defaultInformer)
}

func (f *backendInformer) Lister() apiv0alpha0.BackendLister {
	return apiv0alpha0.NewBackendLister(f.Informer().GetIndexer())
}
