//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v0alpha0

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendDestination) DeepCopyInto(out *BackendDestination) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]BackendPort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FQDN != nil {
		in, out := &in.FQDN, &out.FQDN
		*out = new(FQDNBackend)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ServiceBackend)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendDestination.
func (in *BackendDestination) DeepCopy() *BackendDestination {
	if in == nil {
		return nil
	}
	out := new(BackendDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendExtension) DeepCopyInto(out *BackendExtension) {
	*out = *in
	if in.RawConfig != nil {
		in, out := &in.RawConfig, &out.RawConfig
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendExtension.
func (in *BackendExtension) DeepCopy() *BackendExtension {
	if in == nil {
		return nil
	}
	out := new(BackendExtension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendPort) DeepCopyInto(out *BackendPort) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(BackendTLS)
		(*in).DeepCopyInto(*out)
	}
	if in.ProtocolOptions != nil {
		in, out := &in.ProtocolOptions, &out.ProtocolOptions
		*out = new(BackendProtocolOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendPort.
func (in *BackendPort) DeepCopy() *BackendPort {
	if in == nil {
		return nil
	}
	out := new(BackendPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendProtocolOptions) DeepCopyInto(out *BackendProtocolOptions) {
	*out = *in
	if in.MCP != nil {
		in, out := &in.MCP, &out.MCP
		*out = new(MCPProtocolOptions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendProtocolOptions.
func (in *BackendProtocolOptions) DeepCopy() *BackendProtocolOptions {
	if in == nil {
		return nil
	}
	out := new(BackendProtocolOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendTLS) DeepCopyInto(out *BackendTLS) {
	*out = *in
	if in.CaBundleRef != nil {
		in, out := &in.CaBundleRef, &out.CaBundleRef
		*out = make([]v1.ObjectReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InsecureSkipVerify != nil {
		in, out := &in.InsecureSkipVerify, &out.InsecureSkipVerify
		*out = new(bool)
		**out = **in
	}
	if in.ClientCertificateRef != nil {
		in, out := &in.ClientCertificateRef, &out.ClientCertificateRef
		*out = new(v1.SecretObjectReference)
		(*in).DeepCopyInto(*out)
	}
	if in.SubjectAltNames != nil {
		in, out := &in.SubjectAltNames, &out.SubjectAltNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendTLS.
func (in *BackendTLS) DeepCopy() *BackendTLS {
	if in == nil {
		return nil
	}
	out := new(BackendTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FQDNBackend) DeepCopyInto(out *FQDNBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FQDNBackend.
func (in *FQDNBackend) DeepCopy() *FQDNBackend {
	if in == nil {
		return nil
	}
	out := new(FQDNBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPProtocolOptions) DeepCopyInto(out *MCPProtocolOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPProtocolOptions.
func (in *MCPProtocolOptions) DeepCopy() *MCPProtocolOptions {
	if in == nil {
		return nil
	}
	out := new(MCPProtocolOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessingMode) DeepCopyInto(out *ProcessingMode) {
	*out = *in
	if in.RequestHeaders != nil {
		in, out := &in.RequestHeaders, &out.RequestHeaders
		*out = new(HeaderProcessingMode)
		**out = **in
	}
	if in.RequestBody != nil {
		in, out := &in.RequestBody, &out.RequestBody
		*out = new(BodyProcessingMode)
		**out = **in
	}
	if in.ResponseHeaders != nil {
		in, out := &in.ResponseHeaders, &out.ResponseHeaders
		*out = new(HeaderProcessingMode)
		**out = **in
	}
	if in.ResponseBody != nil {
		in, out := &in.ResponseBody, &out.ResponseBody
		*out = new(BodyProcessingMode)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessingMode.
func (in *ProcessingMode) DeepCopy() *ProcessingMode {
	if in == nil {
		return nil
	}
	out := new(ProcessingMode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessorBackendRef) DeepCopyInto(out *ProcessorBackendRef) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(v1.Namespace)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(v1.Kind)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessorBackendRef.
func (in *ProcessorBackendRef) DeepCopy() *ProcessorBackendRef {
	if in == nil {
		return nil
	}
	out := new(ProcessorBackendRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBackend) DeepCopyInto(out *ServiceBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBackend.
func (in *ServiceBackend) DeepCopy() *ServiceBackend {
	if in == nil {
		return nil
	}
	out := new(ServiceBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XBackendDestination) DeepCopyInto(out *XBackendDestination) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XBackendDestination.
func (in *XBackendDestination) DeepCopy() *XBackendDestination {
	if in == nil {
		return nil
	}
	out := new(XBackendDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XBackendDestination) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XBackendDestinationControllerStatus) DeepCopyInto(out *XBackendDestinationControllerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XBackendDestinationControllerStatus.
func (in *XBackendDestinationControllerStatus) DeepCopy() *XBackendDestinationControllerStatus {
	if in == nil {
		return nil
	}
	out := new(XBackendDestinationControllerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XBackendDestinationList) DeepCopyInto(out *XBackendDestinationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XBackendDestination, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XBackendDestinationList.
func (in *XBackendDestinationList) DeepCopy() *XBackendDestinationList {
	if in == nil {
		return nil
	}
	out := new(XBackendDestinationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XBackendDestinationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XBackendDestinationSpec) DeepCopyInto(out *XBackendDestinationSpec) {
	*out = *in
	in.Destination.DeepCopyInto(&out.Destination)
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make([]BackendExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XBackendDestinationSpec.
func (in *XBackendDestinationSpec) DeepCopy() *XBackendDestinationSpec {
	if in == nil {
		return nil
	}
	out := new(XBackendDestinationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XBackendDestinationStatus) DeepCopyInto(out *XBackendDestinationStatus) {
	*out = *in
	if in.Controllers != nil {
		in, out := &in.Controllers, &out.Controllers
		*out = make([]XBackendDestinationControllerStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XBackendDestinationStatus.
func (in *XBackendDestinationStatus) DeepCopy() *XBackendDestinationStatus {
	if in == nil {
		return nil
	}
	out := new(XBackendDestinationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XPayloadProcessor) DeepCopyInto(out *XPayloadProcessor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XPayloadProcessor.
func (in *XPayloadProcessor) DeepCopy() *XPayloadProcessor {
	if in == nil {
		return nil
	}
	out := new(XPayloadProcessor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XPayloadProcessor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XPayloadProcessorList) DeepCopyInto(out *XPayloadProcessorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XPayloadProcessor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XPayloadProcessorList.
func (in *XPayloadProcessorList) DeepCopy() *XPayloadProcessorList {
	if in == nil {
		return nil
	}
	out := new(XPayloadProcessorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XPayloadProcessorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XPayloadProcessorSpec) DeepCopyInto(out *XPayloadProcessorSpec) {
	*out = *in
	in.BackendRef.DeepCopyInto(&out.BackendRef)
	if in.ProcessingMode != nil {
		in, out := &in.ProcessingMode, &out.ProcessingMode
		*out = new(ProcessingMode)
		(*in).DeepCopyInto(*out)
	}
	if in.MessageTimeout != nil {
		in, out := &in.MessageTimeout, &out.MessageTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XPayloadProcessorSpec.
func (in *XPayloadProcessorSpec) DeepCopy() *XPayloadProcessorSpec {
	if in == nil {
		return nil
	}
	out := new(XPayloadProcessorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XPayloadProcessorStatus) DeepCopyInto(out *XPayloadProcessorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XPayloadProcessorStatus.
func (in *XPayloadProcessorStatus) DeepCopy() *XPayloadProcessorStatus {
	if in == nil {
		return nil
	}
	out := new(XPayloadProcessorStatus)
	in.DeepCopyInto(out)
	return out
}
