/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v0alpha0

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	apiv0alpha0 "sigs.k8s.io/wg-ai-gateway/prototypes/backend-control-plane/backend/api/v0alpha0"
)

// EgressGatewayLister helps list EgressGateways.
// All objects returned here must be treated as read-only.
type EgressGatewayLister interface {
	// List lists all EgressGateways in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv0alpha0.EgressGateway, err error)
	// EgressGateways returns an object that can list and get EgressGateways.
	EgressGateways(namespace string) EgressGatewayNamespaceLister
	EgressGatewayListerExpansion
}

// egressGatewayLister implements the EgressGatewayLister interface.
type egressGatewayLister struct {
	listers.ResourceIndexer[*apiv0alpha0.EgressGateway]
}

// NewEgressGatewayLister returns a new EgressGatewayLister.
func NewEgressGatewayLister(indexer cache.Indexer) EgressGatewayLister {
	return &egressGatewayLister{listers.New[*apiv0alpha0.EgressGateway](indexer, apiv0alpha0.Resource("egressgateway"))}
}

// EgressGateways returns an object that can list and get EgressGateways.
func (s *egressGatewayLister) EgressGateways(namespace string) EgressGatewayNamespaceLister {
	return egressGatewayNamespaceLister{listers.NewNamespaced[*apiv0alpha0.EgressGateway](s.ResourceIndexer, namespace)}
}

// EgressGatewayNamespaceLister helps list and get EgressGateways.
// All objects returned here must be treated as read-only.
type EgressGatewayNamespaceLister interface {
	// List lists all EgressGateways in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv0alpha0.EgressGateway, err error)
	// Get retrieves the EgressGateway from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv0alpha0.EgressGateway, error)
	EgressGatewayNamespaceListerExpansion
}

// egressGatewayNamespaceLister implements the EgressGatewayNamespaceLister
// interface.
type egressGatewayNamespaceLister struct {
	listers.ResourceIndexer[*apiv0alpha0.EgressGateway]
}
