/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v0alpha0

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	apiv0alpha0 "sigs.k8s.io/wg-ai-gateway/prototypes/backend-control-plane/backend/api/v0alpha0"
)

// XPayloadProcessorLister helps list XPayloadProcessors.
// All objects returned here must be treated as read-only.
type XPayloadProcessorLister interface {
	// List lists all XPayloadProcessors in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv0alpha0.XPayloadProcessor, err error)
	// XPayloadProcessors returns an object that can list and get XPayloadProcessors.
	XPayloadProcessors(namespace string) XPayloadProcessorNamespaceLister
	XPayloadProcessorListerExpansion
}

// xPayloadProcessorLister implements the XPayloadProcessorLister interface.
type xPayloadProcessorLister struct {
	listers.ResourceIndexer[*apiv0alpha0.XPayloadProcessor]
}

// NewXPayloadProcessorLister returns a new XPayloadProcessorLister.
func NewXPayloadProcessorLister(indexer cache.Indexer) XPayloadProcessorLister {
	return &xPayloadProcessorLister{listers.New[*apiv0alpha0.XPayloadProcessor](indexer, apiv0alpha0.Resource("xpayloadprocessor"))}
}

// XPayloadProcessors returns an object that can list and get XPayloadProcessors.
func (s *xPayloadProcessorLister) XPayloadProcessors(namespace string) XPayloadProcessorNamespaceLister {
	return xPayloadProcessorNamespaceLister{listers.NewNamespaced[*apiv0alpha0.XPayloadProcessor](s.ResourceIndexer, namespace)}
}

// XPayloadProcessorNamespaceLister helps list and get XPayloadProcessors.
// All objects returned here must be treated as read-only.
type XPayloadProcessorNamespaceLister interface {
	// List lists all XPayloadProcessors in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv0alpha0.XPayloadProcessor, err error)
	// Get retrieves the XPayloadProcessor from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv0alpha0.XPayloadProcessor, error)
	XPayloadProcessorNamespaceListerExpansion
}

// xPayloadProcessorNamespaceLister implements the XPayloadProcessorNamespaceLister
// interface.
type xPayloadProcessorNamespaceLister struct {
	listers.ResourceIndexer[*apiv0alpha0.XPayloadProcessor]
}
