/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v0alpha0

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	apiv0alpha0 "sigs.k8s.io/wg-ai-gateway/prototypes/payload-processor/api/v0alpha0"
)

// PayloadProcessorLister helps list PayloadProcessors.
// All objects returned here must be treated as read-only.
type PayloadProcessorLister interface {
	// List lists all PayloadProcessors in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv0alpha0.PayloadProcessor, err error)
	// PayloadProcessors returns an object that can list and get PayloadProcessors.
	PayloadProcessors(namespace string) PayloadProcessorNamespaceLister
	PayloadProcessorListerExpansion
}

// payloadProcessorLister implements the PayloadProcessorLister interface.
type payloadProcessorLister struct {
	listers.ResourceIndexer[*apiv0alpha0.PayloadProcessor]
}

// NewPayloadProcessorLister returns a new PayloadProcessorLister.
func NewPayloadProcessorLister(indexer cache.Indexer) PayloadProcessorLister {
	return &payloadProcessorLister{listers.New[*apiv0alpha0.PayloadProcessor](indexer, apiv0alpha0.Resource("payloadprocessor"))}
}

// PayloadProcessors returns an object that can list and get PayloadProcessors.
func (s *payloadProcessorLister) PayloadProcessors(namespace string) PayloadProcessorNamespaceLister {
	return payloadProcessorNamespaceLister{listers.NewNamespaced[*apiv0alpha0.PayloadProcessor](s.ResourceIndexer, namespace)}
}

// PayloadProcessorNamespaceLister helps list and get PayloadProcessors.
// All objects returned here must be treated as read-only.
type PayloadProcessorNamespaceLister interface {
	// List lists all PayloadProcessors in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv0alpha0.PayloadProcessor, err error)
	// Get retrieves the PayloadProcessor from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv0alpha0.PayloadProcessor, error)
	PayloadProcessorNamespaceListerExpansion
}

// payloadProcessorNamespaceLister implements the PayloadProcessorNamespaceLister
// interface.
type payloadProcessorNamespaceLister struct {
	listers.ResourceIndexer[*apiv0alpha0.PayloadProcessor]
}
