/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v0alpha0

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	versioned "sigs.k8s.io/wg-ai-gateway/prototypes/payload-processor/api/k8s/client/clientset/versioned"
	internalinterfaces "sigs.k8s.io/wg-ai-gateway/prototypes/payload-processor/api/k8s/client/informers/externalversions/internalinterfaces"
	apiv0alpha0 "sigs.k8s.io/wg-ai-gateway/prototypes/payload-processor/api/k8s/client/listers/api/v0alpha0"
	payloadprocessorapiv0alpha0 "sigs.k8s.io/wg-ai-gateway/prototypes/payload-processor/api/v0alpha0"
)

// PayloadProcessorInformer provides access to a shared informer and lister for
// PayloadProcessors.
type PayloadProcessorInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv0alpha0.PayloadProcessorLister
}

type payloadProcessorInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPayloadProcessorInformer constructs a new informer for PayloadProcessor type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPayloadProcessorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewPayloadProcessorInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewFilteredPayloadProcessorInformer constructs a new informer for PayloadProcessor type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPayloadProcessorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewPayloadProcessorInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewPayloadProcessorInformerWithOptions constructs a new informer for PayloadProcessor type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPayloadProcessorInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	gvr := schema.GroupVersionResource{Group: "ainetworking.x-k8s.io", Version: "v0alpha0", Resource: "payloadprocessors"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.AinetworkingV0alpha0().PayloadProcessors(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.AinetworkingV0alpha0().PayloadProcessors(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.AinetworkingV0alpha0().PayloadProcessors(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.AinetworkingV0alpha0().PayloadProcessors(namespace).Watch(ctx, opts)
			},
		}, client),
		&payloadprocessorapiv0alpha0.PayloadProcessor{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	)
}

func (f *payloadProcessorInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewPayloadProcessorInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *payloadProcessorInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&payloadprocessorapiv0alpha0.PayloadProcessor{}, f.defaultInformer)
}

func (f *payloadProcessorInformer) Lister() apiv0alpha0.PayloadProcessorLister {
	return apiv0alpha0.NewPayloadProcessorLister(f.Informer().GetIndexer())
}
