// Code generated by hand (based on controller-gen deepcopy pattern). Edit as needed.

package v0alpha0

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	gwv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto copies all properties into another PayloadProcessor.
func (in *PayloadProcessor) DeepCopyInto(out *PayloadProcessor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PayloadProcessor) DeepCopy() *PayloadProcessor {
	if in == nil {
		return nil
	}
	out := new(PayloadProcessor)
	in.DeepCopyInto(out)
	return out
}

func (in *PayloadProcessor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PayloadProcessorList) DeepCopyInto(out *PayloadProcessorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PayloadProcessor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PayloadProcessorList) DeepCopy() *PayloadProcessorList {
	if in == nil {
		return nil
	}
	out := new(PayloadProcessorList)
	in.DeepCopyInto(out)
	return out
}

func (in *PayloadProcessorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PayloadProcessorSpec) DeepCopyInto(out *PayloadProcessorSpec) {
	*out = *in
	in.TargetRef.DeepCopyInto(&out.TargetRef)
	if in.Processors != nil {
		in, out := &in.Processors, &out.Processors
		*out = make([]ProcessorEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PayloadProcessorSpec) DeepCopy() *PayloadProcessorSpec {
	if in == nil {
		return nil
	}
	out := new(PayloadProcessorSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ProcessorEntry) DeepCopyInto(out *ProcessorEntry) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.InProcess != nil {
		in, out := &in.InProcess, &out.InProcess
		*out = new(InProcessConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtProc != nil {
		in, out := &in.ExtProc, &out.ExtProc
		*out = new(ExtProcConfig)
		(*in).DeepCopyInto(*out)
	}
}

func (in *ProcessorEntry) DeepCopy() *ProcessorEntry {
	if in == nil {
		return nil
	}
	out := new(ProcessorEntry)
	in.DeepCopyInto(out)
	return out
}

func (in *InProcessConfig) DeepCopyInto(out *InProcessConfig) {
	*out = *in
	in.Request.DeepCopyInto(&out.Request)
}

func (in *InProcessConfig) DeepCopy() *InProcessConfig {
	if in == nil {
		return nil
	}
	out := new(InProcessConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *InProcessTransform) DeepCopyInto(out *InProcessTransform) {
	*out = *in
	if in.Set != nil {
		in, out := &in.Set, &out.Set
		*out = make([]HeaderTransformation, len(*in))
		copy(*out, *in)
	}
	if in.Add != nil {
		in, out := &in.Add, &out.Add
		*out = make([]HeaderTransformation, len(*in))
		copy(*out, *in)
	}
	if in.Remove != nil {
		in, out := &in.Remove, &out.Remove
		*out = make([]HeaderName, len(*in))
		copy(*out, *in)
	}
}

func (in *InProcessTransform) DeepCopy() *InProcessTransform {
	if in == nil {
		return nil
	}
	out := new(InProcessTransform)
	in.DeepCopyInto(out)
	return out
}

func (in *HeaderTransformation) DeepCopy() *HeaderTransformation {
	if in == nil {
		return nil
	}
	out := new(HeaderTransformation)
	*out = *in
	return out
}

func (in *ExtProcConfig) DeepCopyInto(out *ExtProcConfig) {
	*out = *in
	in.BackendRef.DeepCopyInto(&out.BackendRef)
}

func (in *ExtProcConfig) DeepCopy() *ExtProcConfig {
	if in == nil {
		return nil
	}
	out := new(ExtProcConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for inlined shared types

func (in *LocalPolicyTargetReference) DeepCopyInto(out *LocalPolicyTargetReference) {
	*out = *in
}

func (in *LocalPolicyTargetReferenceWithSectionName) DeepCopyInto(out *LocalPolicyTargetReferenceWithSectionName) {
	*out = *in
	in.LocalPolicyTargetReference.DeepCopyInto(&out.LocalPolicyTargetReference)
	if in.SectionName != nil {
		in, out := &in.SectionName, &out.SectionName
		*out = new(gwv1.SectionName)
		**out = **in
	}
}
